In [2]:
# Importing the required libraries
import numpy as np
import pandas as pd
from sklearn.decomposition import PCA

In [3]:
# Importing the data

train = pd.read_csv('train.csv')
test = pd.read_csv('test.csv')

In [4]:
train.head()

,ID,y,X0,X1,X2,X3,X4,X5,X6,X8,...,X375,X376,X377,X378,X379,X380,X382,X383,X384,X385
0,0,130.81,k,v,at,a,d,u,j,o,...,0,0,1,0,0,0,0,0,0,0
1,6,88.53,k,t,av,e,d,y,l,o,...,1,0,0,0,0,0,0,0,0,0
2,7,76.26,az,w,n,c,d,x,j,x,...,0,0,0,0,0,0,1,0,0,0
3,9,80.62,az,t,n,f,d,x,l,e,...,0,0,0,0,0,0,0,0,0,0
4,13,78.02,az,v,n,f,d,h,d,n,...,0,0,0,0,0,0,0,0,0,0

In [5]:
test.head()

,ID,X0,X1,X2,X3,X4,X5,X6,X8,X10,...,X375,X376,X377,X378,X379,X380,X382,X383,X384,X385
0,1,az,v,n,f,d,t,a,w,0,...,0,0,0,1,0,0,0,0,0,0
1,2,t,b,ai,a,d,b,g,y,0,...,0,0,1,0,0,0,0,0,0,0
2,3,az,v,as,f,d,a,j,j,0,...,0,0,0,1,0,0,0,0,0,0
3,4,az,l,n,f,d,z,l,n,0,...,0,0,0,1,0,0,0,0,0,0
4,5,w,s,as,c,d,y,i,m,0,...,1,0,0,0,0,0,0,0,0,0

In [6]:
print('Size of training set: {} rows and {} columns'.format(*train.shape))
print('Size of testing set: {} rows and {} columns'.format(*test.shape))

Size of training set: 4209 rows and 378 columns
Size of testing set: 4209 rows and 377 columns

In [7]:
# Collect the Y values into an array
y_train = train['y'].values

In [8]:
y_train

array([130.81,  88.53,  76.26, ..., 109.22,  87.48, 110.85])

In [10]:
# Understanding the data types 
cols = [c for c in train.columns if 'X' in c]
print('Number of features: {}'.format(len(cols)))
print('Feature types:')
train[cols].dtypes.value_counts()

Number of features: 376
Feature types:

int64     368
object      8
dtype: int64

In [11]:
# Counting the data in each of the columns

counts = [[], [], []]
for c in cols:
    typ = train[c].dtype
    uniq = len(np.unique(train[c]))
    if uniq == 1:
        counts[0].append(c)
    elif uniq == 2 and typ == np.int64:
        counts[1].append(c)
    else:
        counts[2].append(c)
print('Constant features: {} Binary features: {} Categorical features: {}\n'
 .format(*[len(c) for c in counts]))
print('Constant features:', counts[0])
print('Categorical features:', counts[2])

Constant features: 12 Binary features: 356 Categorical features: 8

Constant features: ['X11', 'X93', 'X107', 'X233', 'X235', 'X268', 'X289', 'X290', 'X293', 'X297', 'X330', 'X347']
Categorical features: ['X0', 'X1', 'X2', 'X3', 'X4', 'X5', 'X6', 'X8']

In [13]:
# Split the data
usable_columns = list(set(train.columns) - set(['ID', 'y']))
y_train = train['y'].values
id_test = test['ID'].values
x_train = train[usable_columns]
x_test = test[usable_columns]

## Check for null values and unique values for train & test data

In [14]:
def check_missing_values(df):
    if df.isnull().any().any():
        print('There are missing values in the dataframe')
    else:
        print('There are no missing values in the dataframe')

In [15]:
check_missing_values(x_train)
check_missing_values(x_test)

There are no missing values in the dataframe
There are no missing values in the dataframe

## Label Encoding the categorical values

In [16]:
for column in usable_columns:
    cardinality = len(np.unique(x_train[column]))
    if cardinality == 1:
        x_train.drop(column, axis=1) # Column with only one 
        # value is useless so we drop it
        x_test.drop(column, axis=1)
    if cardinality > 2: # Column is categorical
        mapper = lambda x: sum([ord(digit) for digit in x])
        x_train[column] = x_train[column].apply(mapper)
        x_test[column] = x_test[column].apply(mapper)
x_train.head()

/usr/local/lib/python3.7/site-packages/ipykernel_launcher.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if __name__ == '__main__':
/usr/local/lib/python3.7/site-packages/ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # Remove the CWD from sys.path while we load stuff.

,X350,X110,X105,X18,X218,X88,X343,X307,X285,X22,...,X287,X296,X327,X92,X290,X242,X5,X299,X42,X178
0,0,0,0,1,0,0,0,0,1,0,...,0,0,1,0,0,0,117,0,0,0
1,0,0,0,1,0,0,0,0,1,0,...,0,0,0,0,0,0,121,0,0,1
2,1,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,120,0,0,0
3,1,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,120,0,0,0
4,1,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,104,0,0,0

In [17]:
# Making sure the data is changed into numerical values

print('Feature types:')
x_train[cols].dtypes.value_counts()

Feature types:

int64    376
dtype: int64

## Performing Dimensionality reduction

In [18]:
n_comp = 12
pca = PCA(n_components = n_comp,random_state = 420)
pca2_results_train = pca.fit_transform(x_train)
pca2_results_test = pca.transform(x_test)

## Training using XGBoost

In [19]:
# Training using XGBoost

import xgboost as xgb
from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split

In [20]:
x_train,x_val,y_train,y_val = train_test_split(pca2_results_train, y_train, test_size=0.2, random_state=4242)

In [21]:
d_train = xgb.DMatrix(x_train,label = y_train)
d_val = xgb.DMatrix(x_val,label = y_val)

# dtest = xgb.DMatrix(x_test)

d_test = xgb.DMatrix(pca2_results_test)

In [22]:
params = {}
params['objective'] = 'reg:linear'
params['eta'] = 0.02
params['max_depth'] = 4

def xgb_r2_score(preds, dtrain):
    labels = dtrain.get_label()
    return 'r2', r2_score(labels, preds)
watchlist = [(d_train, 'train'), (d_val, 'valid')]
clf = xgb.train(params, d_train,  1000, watchlist, early_stopping_rounds=50, 
 feval=xgb_r2_score, maximize=True, verbose_eval=10)

[06:31:22] WARNING: /workspace/src/objective/regression_obj.cu:167: reg:linear is now deprecated in favor of reg:squarederror.
[0]	train-rmse:99.14835	valid-rmse:98.26297	train-r2:-58.35295	valid-r2:-67.63754
Multiple eval metrics have been passed: 'valid-r2' will be used for early stopping.

Will train until valid-r2 hasn't improved in 50 rounds.
[10]	train-rmse:81.27653	valid-rmse:80.36433	train-r2:-38.88428	valid-r2:-44.91014
[20]	train-rmse:66.71610	valid-rmse:65.77334	train-r2:-25.87403	valid-r2:-29.75260
[30]	train-rmse:54.86912	valid-rmse:53.89136	train-r2:-17.17722	valid-r2:-19.64525
[40]	train-rmse:45.24710	valid-rmse:44.22323	train-r2:-11.36097	valid-r2:-12.90218
[50]	train-rmse:37.44854	valid-rmse:36.37614	train-r2:-7.46723	valid-r2:-8.40622
[60]	train-rmse:31.14584	valid-rmse:30.02252	train-r2:-4.85695	valid-r2:-5.40732
[70]	train-rmse:26.08417	valid-rmse:24.91497	train-r2:-3.10795	valid-r2:-3.41268
[80]	train-rmse:22.04313	valid-rmse:20.83055	train-r2:-1.93371	valid-r2:-2.08449
[90]	train-rmse:18.84670	valid-rmse:17.59590	train-r2:-1.14458	valid-r2:-1.20092
[100]	train-rmse:16.33346	valid-rmse:15.07941	train-r2:-0.61075	valid-r2:-0.61641
[110]	train-rmse:14.39544	valid-rmse:13.14880	train-r2:-0.25118	valid-r2:-0.22901
[120]	train-rmse:12.93004	valid-rmse:11.68792	train-r2:-0.00942	valid-r2:0.02892
[130]	train-rmse:11.81778	valid-rmse:10.61758	train-r2:0.15678	valid-r2:0.19863
[140]	train-rmse:10.98842	valid-rmse:9.84751	train-r2:0.27098	valid-r2:0.31066
[150]	train-rmse:10.37530	valid-rmse:9.30925	train-r2:0.35006	valid-r2:0.38396
[160]	train-rmse:9.92806	valid-rmse:8.95155	train-r2:0.40489	valid-r2:0.43039
[170]	train-rmse:9.59294	valid-rmse:8.70725	train-r2:0.44438	valid-r2:0.46105
[180]	train-rmse:9.34681	valid-rmse:8.54917	train-r2:0.47253	valid-r2:0.48045
[190]	train-rmse:9.15929	valid-rmse:8.44648	train-r2:0.49348	valid-r2:0.49285
[200]	train-rmse:9.02039	valid-rmse:8.37742	train-r2:0.50873	valid-r2:0.50111
[210]	train-rmse:8.92144	valid-rmse:8.34411	train-r2:0.51945	valid-r2:0.50507
[220]	train-rmse:8.83893	valid-rmse:8.32315	train-r2:0.52829	valid-r2:0.50756
[230]	train-rmse:8.76794	valid-rmse:8.30707	train-r2:0.53584	valid-r2:0.50946
[240]	train-rmse:8.72074	valid-rmse:8.30206	train-r2:0.54083	valid-r2:0.51005
[250]	train-rmse:8.67982	valid-rmse:8.29542	train-r2:0.54512	valid-r2:0.51083
[260]	train-rmse:8.63931	valid-rmse:8.29556	train-r2:0.54936	valid-r2:0.51082
[270]	train-rmse:8.60199	valid-rmse:8.29404	train-r2:0.55324	valid-r2:0.51099
[280]	train-rmse:8.57418	valid-rmse:8.29302	train-r2:0.55613	valid-r2:0.51111
[290]	train-rmse:8.54490	valid-rmse:8.29007	train-r2:0.55916	valid-r2:0.51146
[300]	train-rmse:8.51887	valid-rmse:8.28973	train-r2:0.56184	valid-r2:0.51150
[310]	train-rmse:8.49962	valid-rmse:8.28719	train-r2:0.56381	valid-r2:0.51180
[320]	train-rmse:8.47590	valid-rmse:8.28692	train-r2:0.56625	valid-r2:0.51183
[330]	train-rmse:8.45273	valid-rmse:8.28591	train-r2:0.56861	valid-r2:0.51195
[340]	train-rmse:8.42706	valid-rmse:8.28291	train-r2:0.57123	valid-r2:0.51231
[350]	train-rmse:8.40655	valid-rmse:8.28187	train-r2:0.57332	valid-r2:0.51243
[360]	train-rmse:8.37478	valid-rmse:8.27871	train-r2:0.57653	valid-r2:0.51280
[370]	train-rmse:8.35338	valid-rmse:8.27615	train-r2:0.57870	valid-r2:0.51310
[380]	train-rmse:8.32636	valid-rmse:8.27505	train-r2:0.58142	valid-r2:0.51323
[390]	train-rmse:8.30156	valid-rmse:8.27354	train-r2:0.58391	valid-r2:0.51341
[400]	train-rmse:8.27080	valid-rmse:8.27151	train-r2:0.58698	valid-r2:0.51365
[410]	train-rmse:8.24436	valid-rmse:8.26912	train-r2:0.58962	valid-r2:0.51393
[420]	train-rmse:8.22183	valid-rmse:8.26700	train-r2:0.59186	valid-r2:0.51418
[430]	train-rmse:8.19258	valid-rmse:8.26488	train-r2:0.59476	valid-r2:0.51443
[440]	train-rmse:8.17196	valid-rmse:8.26348	train-r2:0.59680	valid-r2:0.51459
[450]	train-rmse:8.14747	valid-rmse:8.26325	train-r2:0.59921	valid-r2:0.51462
[460]	train-rmse:8.12475	valid-rmse:8.26039	train-r2:0.60144	valid-r2:0.51495
[470]	train-rmse:8.09905	valid-rmse:8.26316	train-r2:0.60396	valid-r2:0.51463
[480]	train-rmse:8.07695	valid-rmse:8.26383	train-r2:0.60612	valid-r2:0.51455
[490]	train-rmse:8.05147	valid-rmse:8.26022	train-r2:0.60860	valid-r2:0.51497
[500]	train-rmse:8.02818	valid-rmse:8.26067	train-r2:0.61086	valid-r2:0.51492
[510]	train-rmse:7.99995	valid-rmse:8.26045	train-r2:0.61359	valid-r2:0.51495
[520]	train-rmse:7.97765	valid-rmse:8.26214	train-r2:0.61574	valid-r2:0.51475
[530]	train-rmse:7.95240	valid-rmse:8.26602	train-r2:0.61817	valid-r2:0.51429
[540]	train-rmse:7.93429	valid-rmse:8.26628	train-r2:0.61991	valid-r2:0.51426
Stopping. Best iteration:
[492]	train-rmse:8.04721	valid-rmse:8.25907	train-r2:0.60901	valid-r2:0.51511

## Predict test_df using XGBoost

In [23]:
p_test = clf.predict(d_test)

In [24]:
sub = pd.DataFrame()
sub['ID'] = id_test
sub['y'] = p_test
sub.to_csv('test_df.csv', index = False)
sub.head()

   ID           y
0   1   83.213921
1   2   97.956253
2   3   83.240112
3   4   77.025482
4   5  112.554588